services:
  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: Europe/Warsaw
    container_name: user-php
    volumes:
      - ./:/app
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
      - php_composer_data:/root/.composer
    networks:
      - sandbox-network
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  user-www:
    build: ./docker/www
    container_name: user-www
    ports:
      - 8082:80
    volumes:
      - ./:/app
      - ./docker/www/conf.d:/etc/nginx/conf.d
    networks:
      - sandbox-network
    depends_on:
      php:
        condition: service_healthy

  user-db:
    image: postgres:latest
    container_name: user-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Warsaw
    volumes:
      - user_db_data:/var/lib/postgresql/data   # <- zmienione na domyÅ›lny katalog Postgresa
    ports:
      - 5434:5432
    networks:
      - sandbox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user_db_data:
  php_composer_data:

networks:  
  sandbox-network:
    external: true
    name: sandbox-network
